language: c
env:
- secure: "tAbUBMNusAs14BegrQMjfRtqndfveAruw3kTD2QcUMFyxgWuORj3tuiigjvkr4Uk+VwY6NYHFWZycqxSJu0uBVwpWpvTgl9sInNMlLSXBEXSobtxLiDlOrDFudB5duu0VNYbSZOVOAKyeVvn7mAUjOvS6ZrKa15AYWye+qYCYj4="
script:
- |
  rm -rf _sub.sh
  mkdir _sub.sh
  cd _sub.sh
- |
  echo sub.sh > CNAME
  touch .nojekyll
  cp ../sub.sh index.html
- |
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/sub.sh"
  git init
  git config user.name "Heungsub Lee"
  git config user.email "sub@subl.ee"
  git add .
  git commit -m "deploy sub.sh of subleenv-$TRAVIS_COMMIT"
  git push -qf $REPO master:gh-pages > /dev/null 2>&1
