language: c
env:
- secure: "BROwSqbfvFmIHWp6ncFBWR4tSWGlhuDxKp/VWcswhevWbsgiLgy9vTr7ZtVA5YtSUGkluJKEAdxply5U2syqcEdtC42Qy/hhFkjnycU1p1DKUkMPf/5G3+ILbkRw8CByfdDmQrZ0U+hvi30z2VLKp0DW0BX8rjDXkTKDq3+S3YA="
script:
- mkdir sub.sh-web
  cd sub.sh-web
- echo sub.sh > CNAME
  touch .nojekyll
  cp ../sub.sh index.html
- git init
  git config user.name "Heungsub Lee"
  git config user.email "sub@subl.ee"
  git add .
  git commit -m "deploy sub.sh"
  git push -f "https://$GITHUB_TOKEN@github.com/sublee/sub.sh" master:gh-pages
