language: python
python: 2.7
sudo: required
services:
- docker
env:
- secure: "tAbUBMNusAs14BegrQMjfRtqndfveAruw3kTD2QcUMFyxgWuORj3tuiigjvkr4Uk+Vw\
           Y6NYHFWZycqxSJu0uBVwpWpvTgl9sInNMlLSXBEXSobtxLiDlOrDFudB5duu0VNYbSZ\
           OVOAKyeVvn7mAUjOvS6ZrKa15AYWye+qYCYj4="
script:
- |
  docker run -it --name subenv -v $PWD/sub.sh:/sub.sh ubuntu:14.04 /sub.sh
  docker start -ia subenv
after_success:
- |
  rm -rf _sub.sh
  mkdir _sub.sh
  cd _sub.sh
- |
  echo sub.sh > CNAME
  touch .nojekyll
  python ../sub.sh-web/build.py .
- |
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/sub.sh"
  git init
  git config user.name "Heungsub Lee"
  git config user.email "sub@subl.ee"
  git add .
  git commit -m "Deploy sub.sh from subenv-$TRAVIS_COMMIT"
  git push -qf $REPO master:gh-pages > /dev/null 2>&1
