language: python
python: 2.7
sudo: required
services:
- docker
env:
  global:
  - secure: "tAbUBMNusAs14BegrQMjfRtqndfveAruw3kTD2QcUMFyxgWuORj3tuiigjvkr4Uk+\
             VwY6NYHFWZycqxSJu0uBVwpWpvTgl9sInNMlLSXBEXSobtxLiDlOrDFudB5duu0VN\
             YbSZOVOAKyeVvn7mAUjOvS6ZrKa15AYWye+qYCYj4="
  matrix:
  - IMAGE=ubuntu:16.04
  - IMAGE=ubuntu:14.04
script:
- docker run -it --name subenv -v "$PWD/sub.sh:/sub.sh" "$IMAGE" /sub.sh
- docker start -ia subenv
after_success:
- |
  curl -Lo travis_after_all.py \
    https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  python travis_after_all.py https://api.travis-ci.com
  if [[ -f .to_export_back ]]
  then
    export $(cat .to_export_back)
    if [[ "$BUILD_LEADER" != YES ]] || \
       [[ "$BUILD_AGGREGATE_STATUS" != others_succeeded ]]
    then
      exit
    fi
  fi
- |
  rm -rf _sub.sh
  mkdir _sub.sh
  cd _sub.sh
- |
  echo sub.sh > CNAME
  touch .nojekyll
  python ../sub.sh-web/build.py .
- |
  export REPO="https://$GITHUB_TOKEN@github.com/sublee/sub.sh"
  git init
  git config user.name "Heungsub Lee"
  git config user.email "sub@subl.ee"
  git add .
  git commit -m "Deploy sub.sh from subenv-$TRAVIS_COMMIT"
  git push -qf $REPO master:gh-pages > /dev/null 2>&1
